### ISSUE TITLE
Data Version == 1?

### ISSUE THREAD

**Issue by twitchyliquid64** [mcrute/ubntmfi#2]
Hi,

All my devices are informing with data version == 1, instead of 0 like in your analysis. Have you seen this? If yes, have you been able to fully decode the corresponding payload?

For data version == 1, it seems to be encrypted in the same way, and decrypting results in readable text interspersed with garbage. I think I can see the constructs of JSON in there too.

**Comment by twitchyliquid64** [comment]
I spoke too soon - I've worked it out. If Data-version==1:

 - Bit 0x3 is set (symbolizing snappy compression)
 - Snappy compression is used

:D

**Comment by mcrute** [comment]
What hardware is using version 1? I primarily wrote this for mfi and older Unifi products but I'm more than happy to take patches for newer hardware.

**Comment by twitchyliquid64** [comment]
Ubiquiti AP AC LR.

Correction: 0x4 bit is set to symbolize snappy compression.

I can decode AP packets, but still trying to get the AP to accept my packets without Decrypt Error.

I'm working on the Go code for this in another repo, happy to add you in as a collaborator. I think some of the code will be copy-pasteable.

**Comment by mcrute** [comment]
I'm not actively working on this at the moment but I hope to get back around to it soon. I'd be happy to collaborate with you going forward once I have time to get back to this project. The python implementation in the python folder worked circa 2015 on UAP and mFi devices for both read and write so that may set you in the correct direction. Drop me an email (mike at crute dot us) and I'd be happy to discuss more what work I've done if any of it would help you.
